spring.application.name=ifgram
# Ativa o console web do H2 para você testar no navegador
spring.h2.console.enabled=true
# Define um caminho fixo para o console (ex: http://localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# Configura a URL para o banco persistir em memória enquanto o app estiver rodando
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=